((nil . ((tab-width . 2)
     (indent-tabs-mode . t)))
 (c++-mode . ((c-basic-offset . 2)
          (tab-width . 2)
          (indent-tabs-mode . t)
          (compile-command . "cd ../build; make -j4")))
 ((c-mode . ((c-basic-offset . 2)
         (tab-width . 2)
         (indent-tabs-mode . t)
         (compile-command . "cd ../build; make -j4")))))
